name: WelcomeMe
main: dk.monkeyboy.WelcomeMe.WelcomeMe
version: 1.1.0
website:
author: maxx001
description: >
             Welcome message plugin that can be customized to show
             current online players and a message to the user when
             he logs on the server.
commands:
  wm:
    description: Displays the message again or reloads the message.txt file into memory.
    usage: |
           /<command>
           /<command> reload
           Example: /wm - Displays the message again.
           Example: /wm reload - Reloads message.txt into memory. (need OP)
    